name: docker-cloudflare-chanfana-openapi-template

services:
  worker:
    image: node:24-slim
    user: "${UID:-1000}:${GID:-1000}"
    command: [ "npm", "run", "dev" ]
    working_dir: /app
    security_opt:
      - no-new-privileges:true
    ports:
      - "8788:8787"
    environment:
      WRANGLER_SEND_METRICS: false
      NPM_CONFIG_UPDATE_NOTIFIER: false
    env_file:
      - .env.dev
    volumes:
      - .:/app
